=== HugoMartel/network_allocation/data/topology/topology.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/product.schema.json",
    "title": "Topology",
    "description": "Scheme to write a correct topology JSON file",
    "type": "object",
    "properties": {
        "width": {
            "description": "Width of the population density grid",
            "type": "integer"
        },
        "height": {
            "description": "Height of the population density grid",
            "type": "integer"
        },
        "tile_size": {
            "description": "X and Y sizes for a density grid tile in meters",
            "type": "object",
            "properties": {
                "x": {
                    "description": "X size for a density grid tile in meters",
                    "type": "float"
                },
                "y": {
                    "description": "Y size for a density grid tile in meters",
                    "type": "float"
                }
            },
            "required": [
                "x",
                "y"
            ]
        },
        "user_demand": {
            "description": "User demand for the area in bits per second",
            "type": "float"
        },
        "density": {
            "description": "Population density grid with width columns and height rows",
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "integer"
                }
            }
        },
        "pylons": {
            "description": "List of pylons",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "pos": {
                        "description": "Position of the pylon in the grid",
                        "type": "object",
                        "properties": {
                            "x": {
                                "description": "X coordinate of the pylon in meters",
                                "type": "float"
                            },
                            "y": {
                                "description": "Y coordinate of the pylon in meters",
                                "type": "float"
                            },
                            "h": {
                                "description": "Effective height of the pylon in meters",
                                "type": "float"
                            }
                        },
                        "required": [
                            "x",
                            "y",
                            "h"
                        ]
                    }
                },
                "required": [
                    "pos"
                ]
            }
        }
    },
    "required": [
        "width",
        "height",
        "tile_size",
        "user_demand",
        "density",
        "pylons"
    ]
}

=== HugoMartel/network_allocation/data/topology/toy.json
{
    "width": 15,
    "height": 10,
    "tile_size": {"x": 100, "y": 100},
    "user_demand": 1e6,
    "density": [
        [0, 0, 0, 2,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0,  8, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 4, 13, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 3,  6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
        [0, 0, 1, 0,  0, 0, 0, 0, 0, 3, 0, 6, 0, 0, 0],
        [0, 0, 0, 0,  1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
    ],
    "pylons": [
        {"pos": {"x": 1000, "y": 800, "h": 30}},
        {"pos": {"x": 400, "y": 800, "h": 30}},
        {"pos": {"x": 100, "y": 200, "h": 30}},
        {"pos": {"x": 400, "y": 400, "h": 30}},
        {"pos": {"x": 1000, "y": 100,"h": 30}}
    ]
}
